version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:3.8-management'
    hostname: rabbitmq
    ports:
      - "15672:15672" # web
      - "5672:5672" # microservice connects on it
    environment:
      - RABBITMQ_DEFAULT_USER=admin 
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - network

networks:
  network:
    driver: bridge